---
title: "Visualization and EDA 1"
output: github_document
date: "2025-09-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
library(p8105.datasets)
data("weather_df")
```

Basic scatterplot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

Adding geom point

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

Saving output

```{r}
ggp_weather = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) 

ggp_weather + geom_point()

```

Check that rows are missing

```{r}
weather_df %>% 
  filter(is.na(tmax))
```

## Advanced scatterplots

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) + # Change opacity of points - not mapping the alpha, just setting for all points. Helps identify that there are more points 
  geom_smooth(se = FALSE) # removes standard error bar
```

Where you define aesthetics matters

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name, size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE)
```

Faceting

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3, size = 0.8) +
  geom_smooth(se = FALSE) +
  facet_grid(name ~ .)
```

Make a more interesting scatterplot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

Learning assessment

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax_F = tmax * (9/5) + 32,
    tmin_F = tmin * (9/5) + 32
  ) %>% 
  ggplot(aes(x = tmin_F, y = tmax_F)) + 
    geom_point() +
    geom_smooth(se = FALSE, method = "lm")
```

## Small things

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_smooth(se = FALSE)

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name, shape = name)) +
  geom_smooth(se = FALSE) +
  geom_point() ## do the overlay AFTER the points, otherwise it will be covered up by all the points
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
    geom_point(color = 'purple')

## setting vs mapping aesthetics
```

## Univariate plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmin)) +
  geom_histogram(color = 'white', fill = 'red')
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, color = name)) +
  geom_histogram()
```

How would I fix this? facet?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, fill = name)) +
    geom_histogram() +
    facet_grid(name ~ .)
```

Density plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, fill = name)) +
    geom_density(alpha = 0.3)
```

Box plot
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmin)) +
    geom_boxplot(aes(fill = name))
```

violin plot
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmin, fill = name)) +
    geom_violin()
```

ridge plot
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = name)) +
  geom_density_ridges()
```

Learning assessment

```{r}
weather_df %>% 
  ggplot(aes(x = prcp, fill = name)) +
  geom_histogram() +
  facet_grid (name ~ .)

weather_df %>% 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.2)

weather_df %>% 
  filter(prcp > 5, prcp < 1000) %>% 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = 0.2)

weather_df %>% 
  ggplot(aes(x = prcp, y = name)) +
  geom_density_ridges(scale = .85)
```

